services:
  ########################################## FRONTEND VUE (Dev) ##########################################
  frontend:
    container_name: vue-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: dev
    ports:
      - "5173:5173" # On garde pour le dev en direct
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_NEST_API_URL=http://localhost:3000

  ########################################## BACKEND NEST (Dev) ###########################################
  nest:
    container_name: nest-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.nest
      target: dev
    ports:
      - "3000:3000" # On garde pour le dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Variables pour Postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    depends_on:
      - postgres

  ########################################## POSTGRES #####################################################
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db-dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: