version: "3.9"


secrets:
  pg_password:
    external: true

services:
  ########################################## TRAEFIK ##########################################
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "8080:8080" # Dashboard
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mkherraz1@myges.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    deploy:
      mode: global
      update_config:
        parallelism: 1     # 1 conteneur à la fois
        delay: 5s          # attente de 5 s entre chaque mise à jour
        failure_action: rollback
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.educareschool.me`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth-traefik"
      - "traefik.http.middlewares.auth-traefik.basicauth.users=admin:$$apr1$$vKml6Wvz$$G7Wchk2U2numP/43WdGZh."

  ########################################## FRONTEND (Vue) ##########################################
  frontend:
    image: achraf97/projet5iw-frontend:prod
    environment:
      - VITE_NEST_API_URL=http://nest:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`educareschool.me`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-http.rule=Host(`educareschool.me`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure

  ########################################## BACKEND (Nest) ##########################################
  nest:
    image: achraf97/projet5iw-nest:prod
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydb
    secrets:
      - pg_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nest.rule=Host(`api.educareschool.me`)"
      - "traefik.http.routers.nest.entrypoints=websecure"
      - "traefik.http.routers.nest.tls.certresolver=myresolver"
      - "traefik.http.services.nest.loadbalancer.server.port=3000"
      - "traefik.http.routers.nest-http.rule=Host(`api.educareschool.me`)"
      - "traefik.http.routers.nest-http.entrypoints=web"
      - "traefik.http.routers.nest-http.middlewares=redirect-to-https"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure

  ########################################## POSTGRES ##########################################
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydb
      # ici on indique au entrypoint Postgres de lire le mot de passe
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

volumes:
  postgres_data:
  traefik_letsencrypt:
