FROM node:18 AS install
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM install AS dev
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

FROM install AS build
COPY . .
RUN npm run build

FROM node:18-alpine AS production
WORKDIR /app
COPY --from=build /app ./
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start:prod"]
