#!/bin/bash

echo "🚨 RÉPARATION SENDGRID PRODUCTION - SOLUTION FINALE"
echo "=================================================="
echo "✅ Suppression totale de Gmail"
echo "✅ Configuration SendGrid uniquement"
echo "✅ Diagnostic complet"
echo ""

# Build final
echo "📦 Build production final..."
npm run build
if [ $? -ne 0 ]; then
    echo "❌ Erreur de build final"
    exit 1
fi

echo "✅ Build réussi !"
echo ""

# Instructions de réparation en production
echo "🚨 RÉPARATION EN PRODUCTION (URGENT) :"
echo "======================================"
echo ""
echo "Votre ami avait raison, le secret existe peut-être,"
echo "mais le service utilise encore Gmail comme fallback !"
echo ""
echo "1. 🔌 Connexion au serveur :"
echo "   ssh root@educareschool.me"
echo ""
echo "2. 📁 Navigation :"
echo "   cd /home/github/projet5iw/projet5iw-deploy"
echo ""
echo "3. 🔍 DIAGNOSTIC SECRETS :"
echo "   echo '--- Vérification secret SendGrid ---'"
echo "   docker secret ls | grep sendgrid"
echo "   echo ''"
echo "   echo 'Si aucun résultat → secret manquant'"
echo "   echo 'Si sendgrid_api_key apparaît → secret existe'"
echo ""
echo "4a. 🔧 SI LE SECRET N'EXISTE PAS :"
echo "    echo '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' | docker secret create sendgrid_api_key -"
echo ""
echo "4b. 🔧 SI LE SECRET EXISTE DÉJÀ :"
echo "    echo 'Secret OK, le problème était dans le code'"
echo ""
echo "5. 🚀 REDÉPLOIEMENT AVEC NOUVELLES MODIFICATIONS :"
echo "   docker-compose down nest"
echo "   docker-compose build nest --no-cache"
echo "   docker-compose up -d nest"
echo ""
echo "6. 📊 VÉRIFICATION LOGS (IMMÉDIATE) :"
echo "   docker-compose logs nest | tail -50 | grep -E '(SENDGRID|EMAIL|📧)'"
echo ""
echo "7. 🧪 TEST INVITATION :"
echo "   - Allez dans l'interface admin"
echo "   - Créez une invitation"
echo "   - Vérifiez que l'email arrive"
echo ""

# Logs attendus
echo "📋 LOGS ATTENDUS APRÈS RÉPARATION :"
echo "===================================="
echo "✅ Succès :"
echo "   📧 SENDGRID CONFIGURATION FOUND:"
echo "      API Key: ✅ Configured"
echo "   📧 SENDGRID: Starting email send process:"
echo "   ✅ SENDGRID: Email sent successfully!"
echo ""
echo "❌ Échec (secret manquant) :"
echo "   ❌ SENDGRID API KEY MISSING - EMAIL SERVICE DISABLED"
echo "   Secret path: /run/secrets/sendgrid_api_key"
echo ""

# Avantages
echo "🎯 AVANTAGES DE CETTE SOLUTION :"
echo "================================="
echo "✅ Plus de Gmail = plus d'ETIMEDOUT"
echo "✅ SendGrid uniquement = emails garantis"
echo "✅ Erreurs claires si mal configuré"
echo "✅ Logs détaillés pour diagnostic"
echo "✅ Configuration sécurisée Docker"
echo ""

echo "🏆 RÉSOLUTION GARANTIE !"
echo "========================"
echo "Après ce déploiement :"
echo "→ Soit SendGrid fonctionne (secret configuré)"
echo "→ Soit erreur claire (secret manquant)"
echo "→ Mais JAMAIS plus d'ETIMEDOUT Gmail !"
echo ""
echo "🚀 Allez-y, testez maintenant !" 