#!/bin/bash

echo "🔧 CORRECTION SENDGRID SECRET - PRODUCTION"
echo "=========================================="
echo ""

echo "📋 DIAGNOSTIC PRODUCTION:"
echo "========================="
echo ""
echo "1️⃣ CONNEXION AU SERVEUR:"
echo "ssh root@educareschool.me"
echo ""

echo "2️⃣ VÉRIFICATION DU SECRET:"
echo "cd /home/github/projet5iw/projet5iw-deploy"
echo "docker secret ls | grep sendgrid"
echo ""

echo "3️⃣ SI LE SECRET N'EXISTE PAS:"
echo "echo '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' | docker secret create sendgrid_api_key -"
echo ""

echo "4️⃣ VÉRIFICATION DU SECRET CRÉÉ:"
echo "docker secret ls | grep sendgrid"
echo ""

echo "5️⃣ REDÉPLOIEMENT DU SERVICE:"
echo "git pull origin deploy"
echo "docker stack deploy -c docker-compose.swarm.yml projet5iw-deploy"
echo ""

echo "6️⃣ VÉRIFICATION DES LOGS:"
echo "docker service logs projet5iw-deploy_backend --tail 20"
echo ""

echo "🔍 DIAGNOSTIC AVANCÉ:"
echo "===================="
echo ""
echo "Si le secret existe mais ne marche pas:"
echo "1. Vérifier qu'il est bien monté dans le container:"
echo "   docker exec -it \$(docker ps -q -f name=projet5iw-deploy_backend) ls -la /run/secrets/"
echo ""
echo "2. Vérifier le contenu du secret:"
echo "   docker exec -it \$(docker ps -q -f name=projet5iw-deploy_backend) cat /run/secrets/sendgrid_api_key"
echo ""
echo "3. Vérifier les variables d'environnement:"
echo "   docker exec -it \$(docker ps -q -f name=projet5iw-deploy_backend) env | grep SENDGRID"
echo ""

echo "💡 SOLUTION ALTERNATIVE:"
echo "========================"
echo "Si le secret Docker ne fonctionne pas, utiliser une variable d'environnement:"
echo ""
echo "Dans docker-compose.swarm.yml, remplacer:"
echo "   - SENDGRID_API_KEY_FILE=/run/secrets/sendgrid_api_key"
echo "Par:"
echo "   - SENDGRID_API_KEY=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"
echo ""
echo "Et supprimer 'sendgrid_api_key' des secrets du service."
echo ""

echo "🎯 RÉSOLUTION GARANTIE:"
echo "======================"
echo "1. Le secret Docker n'existe pas → Le créer"
echo "2. Le secret existe mais n'est pas accessible → Vérifier les permissions"
echo "3. En dernier recours → Utiliser une variable d'environnement"
echo ""

echo "⚠️  RAPPEL:"
echo "==========="
echo "La clé SendGrid est:"
echo "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"
echo ""
echo "Elle fonctionne parfaitement en local, donc le problème"
echo "est uniquement dans la configuration Docker en production."
echo "" 